{
 "title": "Host  Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "aggregation", "label": "Aggregation Interval", "query": "5s,10s,30s,1m,5m,10m,30m,1h" },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM system WITH KEY = \"host\""
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$host/"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(uptime)\nFROM system\nWHERE $timeFilter AND host =~ /^$host$/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(n_cpus)\nFROM system\nWHERE $timeFilter AND host =~ /^$host$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "iowait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(usage_iowait)\nFROM cpu \nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($aggregation), host\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(usage_system)\nFROM cpu \nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($aggregation), host\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(usage_user)\nFROM cpu \nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($aggregation), host\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(usage_idle)\nFROM cpu \nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($aggregation), host\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(used)\nFROM mem\nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($interval)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(cached)\nFROM mem\nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($interval)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "buffered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(buffered)\nFROM mem\nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($interval)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(free)\nFROM mem\nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($interval)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(total)\nFROM mem\nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($interval)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used $tag_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(used)\nFROM disk\nWHERE $timeFilter AND host =~ /^$host$/ \nGROUP BY time($aggregation), path\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total $tag_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(total)\nFROM disk\nWHERE $timeFilter AND host =~ /^$host$/ \nGROUP BY time($aggregation), path\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(used)\nFROM swap\nWHERE $timeFilter\nGROUP BY time($aggregation)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(total)\nFROM swap\nWHERE $timeFilter\nGROUP BY time($aggregation)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "blocked",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(blocked)\nFROM processes\nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($aggregation)\nfill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "running",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(running)\nFROM processes\nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($aggregation)\nfill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "sleeping",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(sleeping)\nFROM processes\nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($aggregation)\nfill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(total_threads)\nFROM processes\nWHERE $timeFilter AND host =~ /^$host$/\nGROUP BY time($aggregation)\nfill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "switches",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(mean(context_switches), 1s)\nFROM kernel\nWHERE $timeFilter AND host =~ /$host$/\nGROUP BY time($aggregation)\nfill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Disk I/O for /dev/$disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Disk I/O Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(reads), 1s)\nFROM diskio\nWHERE $timeFilter AND host =~ /^$host$/ AND \"name\" =~ /^$disk$/\nGROUP BY time($aggregation)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "writes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(writes), 1s)\nFROM diskio\nWHERE $timeFilter AND host =~ /^$host$/  AND \"name\" =~ /^$disk$/\nGROUP BY time($aggregation)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(read_bytes), 1s)\nFROM diskio\nWHERE $timeFilter AND host =~ /^$host$/ AND \"name\" =~ /^$disk$/\nGROUP BY time($aggregation)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(write_bytes), 1s)\nFROM diskio\nWHERE $timeFilter AND host =~ /^$host$/ AND \"name\" =~ /^$disk$/\nGROUP BY time($aggregation)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(read_time), 1s)\nFROM diskio\nWHERE $timeFilter AND host =~ /^$host$/ AND \"name\" =~ /^$disk$/\nGROUP BY time($aggregation)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(write_time), 1s)\nFROM diskio\nWHERE $timeFilter AND host =~ /^$host$/ AND \"name\" =~ /^$disk$/\nGROUP BY time($aggregation)\nfill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}