{
 "title": "IMDG",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "aggregation", "label": "Aggregation", "query": "5s,10s,30s,1m,5m,30m,1h" },
   {
    "name": "transaction",
    "label": "Operation",
    "query": "label_values(jmeter_requests, requestName)"
   },
   {
    "name": "transactionGroup",
    "query": "jmeter_requests{requestName=\"$transaction\"}"
   },
   { "name": "gatlingWriteInterval", "query": "5" }
  ]
 },
 "panels": [
  {
   "title": "Total TPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_requests{requestName=~\".+XX.+\"}[10s])) by (requestStatus)",
     "legendFormat": "{{requestStatus}}"
    },
    {
     "alias": "PASS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(count)/$gatlingWriteInterval FROM gatling WHERE $timeFilter AND request = 'allRequests' AND status = 'ok' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FAIL",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(count)/$gatlingWriteInterval FROM gatling WHERE $timeFilter AND request = 'allRequests' AND status = 'ko' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_response_time_sum{requestName=~\".+XX.+\", requestName!~\"UC03.+|UC05.+\"}[10s])/rate(jmeter_response_time_count{requestName=~\".+XX.+\", requestName!~\"UC03.+|UC05.+\"}[10s]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(jmeter_response_time{requestName=~\".+XX.+\", requestName!~\"UC03.+|UC05.+\"})",
     "legendFormat": "90pct"
    },
    {
     "expr": "rate(jmeter_response_time_sum{requestName=\"[TC] UC05_XX_PartyWS\"}[10s])/rate(jmeter_response_time_count{requestName=\"[TC] UC05_XX_PartyWS\"}[10s])",
     "legendFormat": "avg MDM"
    },
    {
     "expr": "jmeter_response_time{requestName=\"[TC] UC05_XX_PartyWS\"}",
     "legendFormat": "90pct MDM"
    },
    {
     "alias": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(mean) FROM gatling WHERE $timeFilter AND request != 'allRequests' AND status = 'all' GROUP BY time($__interval), simulation fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "90pct",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percentiles90) FROM gatling WHERE $timeFilter AND request != 'allRequests' AND status = 'all' GROUP BY time($__interval), simulation fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jmeter_running_threads", "legendFormat": "{{nodeName}}: {{threadGroup}}" },
    {
     "alias": "$tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(active) FROM \"gatling.users\" WHERE $timeFilter AND request != 'allUsers' GROUP BY time($__interval), request fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aggregate Report",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n) by (runId, requestName)",
     "legendFormat": "samples"
    },
    {
     "expr": "avg(\n(max_over_time(jmeter_response_time_sum{requestName=~\".+XX.+\"}[${__range_s}s]) - min_over_time(jmeter_response_time_sum{requestName=~\".+XX.+\"}[${__range_s}s]))\n/ (max_over_time(jmeter_response_time_count{requestName=~\".+XX.+\"}[${__range_s}s]) - min_over_time(jmeter_response_time_count{requestName=~\".+XX.+\"}[${__range_s}s]))\n) by (runId, requestName)",
     "legendFormat": "avg"
    },
    {
     "expr": "avg(\navg_over_time(jmeter_response_time{requestName=~\".+XX.+\"}[${__range_s}s])\n) by (runId, requestName)",
     "legendFormat": "90pct"
    },
    {
     "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n) by (runId, requestName)\n/ sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n) by (runId, requestName)",
     "legendFormat": "errors"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(mean) AS Avg FROM gatling WHERE $timeFilter AND request = 'allRequests' AND status = 'all' GROUP BY request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) AS Count FROM gatling WHERE $timeFilter AND request = 'allRequests' AND status = 'all' GROUP BY request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(percentiles95) AS \"95pct\" FROM gatling WHERE $timeFilter AND request = 'allRequests' AND status = 'all' GROUP BY request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(fail)/mean(total)) AS Errors FROM (SELECT sum(count) AS fail FROM gatling WHERE $timeFilter AND request = 'allRequests' AND status = 'ko'),\n(SELECT sum(count) AS total FROM gatling WHERE $timeFilter AND request = 'allRequests' AND status = 'all') WHERE $timeFilter GROUP BY request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 29 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(fail)/mean(total) FROM (SELECT sum(count) AS fail FROM gatling WHERE $timeFilter AND request = 'allRequests' AND status = 'ko'),\n(SELECT sum(count) AS total FROM gatling WHERE $timeFilter AND request = 'allRequests' AND status = 'all')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors per Transaction",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 29 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n) by (runId, requestName)"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(fail)/mean(total)) AS Errors FROM (SELECT sum(count) AS fail FROM gatling WHERE $timeFilter AND request != 'allRequests' AND status = 'ko' GROUP BY request),\n(SELECT sum(count) AS total FROM gatling WHERE $timeFilter AND request != 'allRequests' AND status = 'all' GROUP BY request) WHERE $timeFilter GROUP BY request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 29 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(jmeter_requests{requestName!~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName!~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n) by (runId, responseCode, responseMessage)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_requests{requestStatus=\"FAIL\"}[10s])) by (responseCode)"
    }
   ]
  },
  { "title": "Operation - $transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "TPS - $transaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_requests{requestName=\"$transaction\"}[10s])) by (requestStatus)"
    }
   ]
  },
  {
   "title": "Response Time - $transaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_response_time_sum{requestName=\"$transaction\"}[10s])/rate(jmeter_response_time_count{requestName=\"$transaction\"}[10s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(jmeter_response_time{requestName=\"$transaction\"})",
     "legendFormat": "90pct"
    }
   ]
  },
  {
   "title": "Transaction Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\"^$transactionGroup\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\"^$transactionGroup\"}[${__range_s}s])\n) by (runId, requestName, responseCode, responseMessage)"
    }
   ]
  }
 ]
}