{
 "title": "SLA",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "aggregation", "label": "Aggregation", "query": "5s,10s,30s,1m,5m,30m,1h" },
   {
    "name": "transaction",
    "label": "Operation",
    "query": "label_values(jmeter_requests, requestName)"
   },
   {
    "name": "transactionGroup",
    "query": "jmeter_requests{requestName=\"$transaction\"}"
   },
   { "name": "gatlingWriteInterval", "query": "5" }
  ]
 },
 "panels": [
  {
   "title": "Total TPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_requests{requestName=~\".+XX.+\"}[10s])) by (requestStatus)",
     "legendFormat": "{{requestStatus}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(jmeter_response_time_sum{requestName=~\".+XX.+\"}[10s])/rate(jmeter_response_time_count{requestName=~\".+XX.+\"}[10s]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "avg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(jmeter_response_time{requestName=~\".+XX.+\"})",
     "legendFormat": "90pct"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jmeter_running_threads) by (nodeName, threadGroup)",
     "legendFormat": "{{nodeName}}: {{threadGroup}}"
    }
   ]
  },
  {
   "title": "Sent/Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(avg(rate(jmeter_request_size_in_bytes_sum{requestName=~\".+XX.+\"}[10s])/rate(jmeter_request_size_in_bytes_count{requestName=~\".+XX.+\"}[10s])) by(requestDirection)) * on(requestName) group_left sum(rate(jmeter_requests{requestName=~\".+XX.+\"}[10s]))",
     "legendFormat": "{{requestDirection}}"
    }
   ]
  },
  {
   "title": "Aggregate Report",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n) by (runId, requestName)",
     "legendFormat": "requests"
    },
    {
     "expr": "avg(\n(max_over_time(jmeter_response_time_sum{requestName=~\".+XX.+\"}[${__range_s}s]) - min_over_time(jmeter_response_time_sum{requestName=~\".+XX.+\"}[${__range_s}s]))\n/ (max_over_time(jmeter_response_time_count{requestName=~\".+XX.+\"}[${__range_s}s]) - min_over_time(jmeter_response_time_count{requestName=~\".+XX.+\"}[${__range_s}s]))\n) by (runId, requestName)",
     "legendFormat": "avg"
    },
    {
     "expr": "avg(\navg_over_time(jmeter_response_time{requestName=~\".+XX.+\"}[${__range_s}s])\n) by (runId, requestName)",
     "legendFormat": "90pct"
    },
    {
     "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n) by (runId, requestName)\n/ sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n) by (runId, requestName)",
     "legendFormat": "errors"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 36 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n)\n/ sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\"}[${__range_s}s])\n)"
    }
   ]
  },
  {
   "title": "Errors per Transaction",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 36 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n) by (runId, requestName)"
    }
   ]
  },
  {
   "title": "Error Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 36 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(jmeter_requests{requestName!~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName!~\".+XX.+\", requestStatus=\"FAIL\"}[${__range_s}s])\n) by (runId, responseCode, responseMessage)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_requests{requestStatus=\"FAIL\"}[10s])) by (responseCode)",
     "legendFormat": "{{responseCode}}"
    }
   ]
  },
  { "title": "Operation - $transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "TPS - $transaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_requests{requestName=\"$transaction\"}[10s])) by (requestStatus)",
     "legendFormat": "{{requestStatus}}"
    }
   ]
  },
  {
   "title": "Response Time - $transaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jmeter_response_time_sum{requestName=\"$transaction\"}[10s])/rate(jmeter_response_time_count{requestName=\"$transaction\"}[10s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(jmeter_response_time{requestName=\"$transaction\"})",
     "legendFormat": "90pct"
    }
   ]
  },
  {
   "title": "Transaction Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(jmeter_requests{requestName=~\"^$transactionGroup\"}[${__range_s}s])\n- min_over_time(jmeter_requests{requestName=~\"^$transactionGroup\"}[${__range_s}s])\n) by (runId, requestName, responseCode, responseMessage)"
    }
   ]
  }
 ]
}